services:
  nginx-app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: sot-prod-proxy-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
      - '8081:8081'
    environment:
      TZ: 'Europe/Brussels'
    volumes:
      - /var/lib/docker-compose/sot-prod-proxy-nginx_data:/data
      - /var/lib/docker-compose/sot-prod-proxy-nginx_letsencrypt:/etc/letsencrypt
