services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: sot-prod-portainer
    restart: always
    ports:
      - 9443:9443
      - 8000:8000 # Portainer Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker_data/sot-prod-portainer:/data
    environment:
      TZ: 'Europe/Brussels'
