services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"  # Portainer Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker_data/sot-prod-portainer:/data
    environment:
      TZ: 'Europe/Brussels'
